version: '3.4'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: ["azurite", "-l", "/data", "--blobHost", "0.0.0.0","--loose"]
    volumes:
      - ${USERPROFILE}\azurite:/data:rw
    ports:
      - "10000:10000"
  mssql:
    image: ${DOCKER_REGISTRY-}mssql
    build:
      context: .
      dockerfile: services/sqlserver/Dockerfile
    volumes:
      - '.\services\sqlserver:/opt/script'
      - '.\src\Rosen.EMP.Api\SqlScripts\SqlServer:/opt/script/sql'
    ports:
      - 1433:1433
  rosen.emp.api:
    image: ${DOCKER_REGISTRY-}rosenempapi
    build:
      context: .
      dockerfile: src/Rosen.EMP.Api/Dockerfile
    depends_on:
      - azurite
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=LocalDev.Docker
      - ASPNETCORE_URLS=https://::5001;http://0.0.0.0:5000
      - ASPNETCORE_HTTPS_PORT=44395
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=/root/.nuget/fallbackpackages2
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages;/root/.nuget/fallbackpackages2
    ports:
      - "54092:5000"
      - "44395:5001"
    volumes:
      - ${USERPROFILE}\vsdbg\vs2017u5:/remote_debugger:rw
      - .\Rosen.EMP.Api:/app
      - .:/src
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${USERPROFILE}\.nuget\packages\:/root/.nuget/fallbackpackages2
      - 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages'